name: SSH into Server and Run Command

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /home/admin/test
          git pull
          chmod 755 run_bot.sh
          /usr/bin/python3 /home/admin/test/bot buy
